language: python
python:
  - "3.6"
services:
  - mysql
  - postgresql
before_install:
  - pip install pycodestyle
  - python3 setup.py install
before_script:
  - psql -c 'create database my_db;' -U postgres
  - mysql -e 'CREATE DATABASE my_db;'
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest