databases:
    db1: # Unique tag
        engine: postgresql # Engine name (`postgresql` pr `mysql`)
        host: 127.0.0.1 # Database host
        port: 5432 # Database port
        user: travis # Username
        password: '' # Optional password
        db: my_db # Database name
        # sslmode: require
        # sslcert: /path/to/client-cert.pem
        # sslkey: /path/to/client-key.pem
        # sslrootcert: /etc/ssl/certs/your-ca-cert.pem
        # sslcrl: /etc/ssl/certs/crl.pem # Optional SSL certificate revocation list
        # sslcompression: 1
        path: /path/to/migrations/ # Path to the migration folder
        pre_migration: '' # Optional queries ran before migrating
        post_migration: 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gab; GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO gab' # Optional queries ran after migrating
    db2:
        engine: mysql
        host: 127.0.0.1
        port: 3306
        user: travis
        password: ''
        db: my_db
        # ssl_check_hostname: true # set to false to disable hostname checking of the server cert
        # ssl_cert: /path/to/client-cert.pem
        # ssl_key: /path/to/client-key.pem
        # ssl_ca: /etc/ssl/certs/your-ca-cert.pem
        # ssl_cipher: 'cipher-name'
        # ssl_capath: /path/to/ca-certs/
        path: /path/to/migrations/
        pre_migration: ''
        post_migration: ''
